### ISSUE TITLE
Add Query Performance Metrics output to log

### ISSUE THREAD

**Issue by jofultz** [retaildevcrews/helium#114]
## Description

As a developer, I'd like to be able to turn on Query Performance Metrics output to the log via a configuration change so that I may gather more information on queries and use that information for debugging and in communication.  I should be able to enable metrics for all queries or for degraded queries only.

## Acceptance Criteria

- [ ] Should be able to enable all Query Performance Metrics and see them in the log.
- [ ] Should be able to enable degraded Query Performance Metrics and see metrics only for degraded queries in the log.
- [ ] Should be able to disable Query Performance Metrics and see no metrics in the log.

## Tasks

**_Assignee should break down work into tasks here_**

- [ ] identify impacted code files where CosmosDB queries are issued
- [ ] design perf metric retrieval and mechanism to pass it back to log persistence layer
- [ ] add configuration setting and enumerate values in comments
- [ ] add code to relevant locations in logging (and DAL if needed) to act on the configuration value

## Done Checklist:
_[Remove items that are not required for task]_
- [ ] Code changes reviewed & signed off
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] Code changes checked into master
- [ ] All existing automated tests (unit and/or e2e) pass successfully, new tests added as needed
- [ ] CI completes successfully
- [ ] CD completes successfully
- [ ] New changes in smoke test for 48hrs
