### ISSUE TITLE
Helium: Checkpoint Review

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#191]
## Checkpoint Review

- M5, January 2020
- Review Date:  30 Jan 2020

### Demo
- Observability (Anne)
- https://aka.ms/heliumdashboard
- [x] Demo completed

### "DoneLog" Review

- [x] _**What was planned to be done this month?**_

- Originally the M5 goal was to complete the Typescript & Java Spring-Boot versions of Helium, along with getting C# & IMDb to done-done.
- Continuous improvement to engineering fundamentals per Retro & Checkpoint feedback.

- [x] _**What was actually done this month?**_

- Successfully met Success Criteria & DoD for C# and IMDb [Issues: #107, #130] 
- Piloted and completed DoD Reviews [#130]
- Focused on submitting small PRs to drive velocity, team has successfully closed 211 Issues in M5, which ends Thursday 1/30/2020: [Helium Kanban Board](https://github.com/orgs/retaildevcrews/projects/1#column-7483739)
- Adopted [IETF draft standards](https://inadarei.github.io/rfc-healthcheck/) for health checks  (retaildevcrews/helium#111) 
- Deployed e2e testing & observability for all languages (Typescript, Java Spring-Boot, C#) https://aka.ms/heliumdashboard
- CI/CD implemented using GitHub Actions workflow to build and push images tagged based on version, tag or PR to master. [Issue: #102, Tasks include: #125, #126, #127]
- Continued improvement in Engineering Fundamentals: [Link to templates](https://github.com/retaildevcrews/helium/issues/new/choose), Issues #128, #150, #73, #117, #116, #89, #72, #140
 
- [x] _**Changes in plan versus last**_

- During M5, we adjusted milestone goal to be API compatible across all languages  
- Started shifting from individual language environments to a consolidated environment [Issue: #103]
- Based on feedback, moving from Java repository pattern (due to CosmosDB differences) to MVC; CSE feedback submitted:
    - [[Azure-Key-Vault spring sdk] - Unable to access Key Vault MSI on Local Dev](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/256077)
    - [[Azure-Key-Vault spring sdk] - Incorrect doc , version doesnt work](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/262008)
    - [[Azure-CosmosDB spring sdk] - Does not not support reading different document types in the same collection](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/264307)
    - [[Azure-CosmosDB spring sdk] - Single document read calls querydocument and not readdocument internally](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/261697)
    - [[Azure-CosmosDB spring sdk] - Support for GetRequestCharge](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/261698)
    - [[Azure-CosmosDB spring sdk] - Does not support cross-document or cross-collection joins](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/256033) 
    - [[Azure-CosmosDB spring sdk] - @Query annotation not supported](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/254390)
    - [[Azure-Application-Insights spring sdk] Unable to implement logging with Application Insights based on docs using config based injection](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/274494)
    - [[Azure-Application-Insights spring sdk] appinsights.jar to be published to maven repo](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/328355)

- [x] _**Key design decisions and their outcomes**_

- Observability: Implemented IETF health checks to standardize results across languages [Issues: #138, #112, #90]
- CI/CD: Implemented CI/CD within GitHub directly using GitHub Actions; Per internal documentation GitHub enterprise will be the preferred DevOps tool [Issue: #102, Tasks include: #125, #126, #127]
- All issues that need Design review are tagged: [Complete view](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label:%22design+review%22)

### Key Project Risks and Concerns

- [x] _**Present Retro**_

- Completed 3 sprints for M5; leveraging Retrospected (working on implementing private instance)
- Key Outcomes: 

    1. **Team Dynamics**:  The team continues to deliver high quality while working remotely, and creating an strong agile environment (not afraid to try new things). 
    2. **Engineering Excellence**: Team maintain quality of work while increasing velocity in M5 (smaller PRs, no regression); M5 continues to drive forward progress around ceremonies & GitHub best practices; Added additional level of review by evaluating engagement against Engineering Survey
    3. **Sharing is Caring**:  Team identified opportunities to share within CSE & outside of CSE, focus will be on creating those assets in M6
    4. **Engineering Survey (#153)**:  The main opportunities for improvement where around branching policies and CI/CD; both will be addressed in M6.

- Complete details: Sprint 2 #139, Sprint 3 #147; Added Engineering Survey in Sprint 3 #153 

- [x] _**Discuss open risks and mitigation plans**_
- Adding 2 additional SEs for M6
- Found Java repository issue and mitigating by moving to MVC (retaildevcrews/Helium-java#29) 
- All bugs are in process of being resolved or scheduled for M6: [Bug list](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Abug)

### Backlog Review

- [x] _**What is the planned for work in future sprints?**_
- Backlog is updated and prioritized during sprint planning every Friday; New issues are added to triage for prioritization.  [Link to Backlog](https://github.com/orgs/retaildevcrews/projects/1#column-7483734)
- Consolidate environments to show consolidation for cost savings, operational efficiency while keeping security boundaries in place. #103
- Done-done on all repos #129,#120, #119
- Create / update Managed Identity - Key Vault repos on github/Microsoft #195
- Create / update IETF health check repos on github.com/Microsoft #197
- Investigate leveraging helium as basis for Java Open Hack #184 
- Creating shareable assets including Redbook slides (#178, #171, #143, #177), Webcast (#168, #142, #144, #154) and documentation (#167, #179),[Complete view](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Asharing)

- [x] _**Is additional checkpoint review needed?**_
- [ ] _**Is additional Game Plan review needed?**_

### Tasks

- [x] _**Upload checkpoint review to Artifact Hub**_
- [x] _**Create Checkpoint Review issue if needed**_

**Comment by evillgenius75** [comment]
@dsturgell comments amended.
