### ISSUE TITLE
Checkpoint Review - M6

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#202]
This checklist is for verifying the necessary details for a checkpoint review. 

## Checkpoint Review

- [ Milestone, Period]
- Review Date: 

### Demo
_Encouraged to just replay "best of" Sprint Demo_

- [ ] Demo completed

### "DoneLog" Review

- [ ] What was planned to be done this month?
- [ ] What was actually done this month?
- [ ] Changes in plan versus last
- [ ] Key design decisions and their outcomes

### Key Project Risks and Concerns

- [ ] Present Retro
- [ ] Discuss open risks and mitigation plans

### Backlog Review

- [ ] What is the planned for work in future sprints?
- [ ] Is additional checkpoint review needed?
- [ ] Is additional Game Plan review needed?

### Tasks

- [ ] Upload checkpoint review to Artifact Hub
