### ISSUE TITLE
Retrospective - M6 - Sprint 2

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#215]
### Link 
https://retrospected.com/game/zqdeonq1

### Summary

# Retrospected Session

### Session details:

**Date**: Friday, February 14th, 2020 at 12:14:18 PM GMT-06:00

**URL**: https://retrospected.com/game/zqdeonq1

**Posts**: 22

**Votes**: 123

#### Liked

- (+6/-0) GH Github actions that auto move issues & PRs - working smoothly in Lithium Repo 
- (+5/-0) Team dynamic
- (+4/-0) Taking on new Flux based direction for Java.
- (+4/-0) Back to focusing on helium
- (+4/-0) Team's resolve to fix quality and developer experience issues
- (+3/-0) More GitHub Action s to automate our Ceremonies

  
#### Learned

- (+10/-0) How to SSH into a running Web App container on Azure! 
- (+9/-0) How to solve our long-time Java security issue with a good developer experience!
- (+0/-0) CICD Rules when it works OK

  
#### Lacked

- (+19/-0) Clear prioritization of backlog - when add new items, just pulled over & shifts order of tasks
  - (+9/-0) Consistent handling and validation of service params.
- (+8/-0) Even though developer experience is a key success metric, our DE is lacking and not up to our quality bar.
- (+6/-0) 2 reviewer approvals on each PR.  This is a suggestion to help get more eyes on code changes.  Could potentially add one reviewer with language expertise, and one without to help everyone get familiar with different repos/languages. 
- (+6/-0) Lack of discipline around labels in Kanban boards; repeating bad habits across repos
  - (+6/-0) We missed a major code quality bar by not testing thoroughly.
- (+4/-0) Lack of focus on fixing gelato performance issue caused invalid test results for weeks.
 - (+3/-0) Full documentation/understanding of differences between Helium languages were not properly captured.  
- (+0/-0) Understanding of why AppService CD is not consistent

  
#### Longed For

- (+5/-0) Consistency for developer experience across languages.
- (+5/-0) Clear succinct design reviews.
 - (+4/-0) Following the spec
- (+3/-0) A solution/explanation for the sherbet crashes due to memory issues. 

### Action Items
- [ ] Spike - research options (auto/pins); Maybe prioritize on right now (next week) vs long term; sprint burnout column (planning would move them into here) - could be a tag; S3 - Sprint column ; Bug (tag/Pri1) move to Sprint column)
- [ ] Change rules to update approvers - Helium (2 reviewer), code repo (2 reviewers)(BART to update); Make sure you add comments in review; Large changes require design review & code review; Design review is most important; Freedom to do pr reviews if you want; Maybe explore Teams Channel (GH addins) - for now, add a note in teams channel (in 15m want to discuss pr #xyz)
- [ ] 1ES - Could they come give a best practice/review/training for the team? (Bart/Deanna)
 - [ ]  Not 100% dedicated to a single project, need to find balance/time to ensure projects are moving along properly
- [ ] Required for: new code, changing existing behavior/boundaries, can be able to add at any time; if doing PR & see alot of changes - block and require a design review;  determine if needed during triage, PR code changes, as you determine scope & feel like it's needed; leverage design review template, add tag, & schedule --anyone can call for Review (like "Table")

### Tasks
- [X] Add Retro summary into Issue
- [x] Create issues for relevant action items
