### ISSUE TITLE
Retrospective - M6 - Sprint 3

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#216]
### Session details:

**Date**: Monday, February 24th, 2020 at 12:09:50 PM GMT-06:00

**URL**: https://retrospected.com/game/V9MXE8AG

**Posts**: 16

**Votes**: 84

#### Liked

- (+8/-0) Made the tough decision to start over on helium-java because it was the "right" thing to do
- (+7/-0) More thoughtful PR reviews and quality questions are being asked
- (+6/-0) Marco joining the helium team!
 - (+6/-0) Team's collaboration and willingness to help and unblock others
- (+4/-0) Most of the team was able to focus a lot of time on helium this sprint
- (+3/-0) Team's commitment to the Quality & Dev Experience focus
- (+3/-0) Reaction to last week's brutal retro was overwhelmingly positive and focused on getting better every week
- (+3/-0) We met our 24 hour SLA on PR reviews by 2 people

  
#### Learned

- (+10/-0) The Github API stinks for Project Board Management
- (+5/-0) I learned more about Java and spring boot

  
#### Lacked

- (+7/-0) I would like for all of our meetings to be as efficient as our stand ups and think pre-reading material, prep and focus would help
 - (+3/-0) Issues took longer than size estimates without being raised as a blocker
- (+2/-0) More discipline around sizing and priority is needed

  
#### Longed For

- (+7/-0) Java KV SDK working correctly
- (+6/-0) A way to easily sort/prioritize items in Github
- (+4/-0) Estimates help us determine what can be accomplished in each sprint and allow us to properly manage the milestone & sprint backlogs

### Action Items
- Leverage Discussions in GH for design reviews for next sprint
- Add sizing sprint planning, leverage block tag if taking longer - discuss during triage & either get help, breakpart, or have spike to investigate
- [x] Add "Block" tag (RED) across all repos
- [x] Ask on 1ES call for best practices; slow for adding notes (writing in another tool & pasting)

### Tasks
- [X] Add Retro summary into Issue
- [X] Create issues for relevant action items
- [ ] If final sprint for milestone. create milestone summary to share
