### ISSUE TITLE
Helium: Checkpoint Review (M6)

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#222]
## Checkpoint Review

- M6, March 2020
- Review Date: 11 March 2020

### "DoneLog" Review

- [x] What was planned to be done this month?

- Originally the M6 goal was to get to done-done on Typescript, Java Spring-Boot, and WebValidate   #120, #119, #129 

- Continuous improvement on engineering fundamentals per Retro & Checkpoint feedback.

- [x] What was actually done this month?
- On-boarded 5 additional team members (3 SEs, 1 LEAPer, and 1 SME) 
- Met Success Criteria & DoD for WebValidate #129 
- Deep focus on Quality and Dev Experience across all repos [M6](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=milestone%3Am6)
   - Improved security: Enforced a requirement to specify the authentication type to use (MSI, CLI, or VS) and fail if invalid. (retaildevcrews/helium-csharp/issues/58, retaildevcrews/helium-typescript/issues/75)
      - Default chaining behavior made it easy to accidentally or maliciously fall back on clear-text environment variables storing credentials.  Currently working with product group to make sure CLI credentials are supported in new SDK's. 
    - Defined invalid parameters for API calls and expected responses/handling - ([Helium API behavior spec](https://github.com/retaildevcrews/helium/blob/master/docs/ParameterValidation.md)).
    - WebValidate: Added additional tests, including unit tests, and added logging to Application Insights to enhance observability in dashboard - [Tasks](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Awebv+milestone%3Am6)
    - Bug fixing across all documentation and apps: [List of bugs fixed in M6](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Abug+milestone%3Am6)

- Consolidated environments for cost savings and operational efficiency while keeping security boundaries in place. #103

- CI-CD (with end-to-end testing in WebValidate - retaildevcrews/webvalidate/issues/26) using Github Actions.  A failing build blocks a PR from merging to master.  Container image is pushed to ACR and Dockerhub. #206, #209, #208, #207 

- Created terraform project to quickly stand up the consolidated Helium environment.  (https://github.com/retaildevcrews/helium-iac)

- Began transition of Spring Boot to fully asynchronous framework [Java Issues](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Ajava)

    - Java Spring Boot:  Moving from synchronous MVC framework to WebFlux asynchronous framework [Java Issues](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Ajava)

    - Java Spring Boot:  Moving from repository pattern to data access objects pattern enabling additional security and cost efficiency. Working with Cosmos product group to document findings. [Java Issues](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Ajava)

- [ ] Changes in plan versus last

- After M6 Sprint 1, we adjusted milestone goal to focus on:

  - Transition of Spring Boot to asynchronous framework [Java Issues](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Ajava)

  - Java SDK feedback to the product group in preparation for a ScottGu review.

    - Quality & Dev Experience across all Helium repos [M6](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=milestone%3Am6)

- [ ] Key design decisions and their outcomes

- Parameter Validation: Defining the expected behavior for invalid api parameters and ensuring consistency across repos (#243, retaildevcrews/webvalidate#24, retaildevcrews/helium-typescript#69, retaildevcrews/helium-typescript#70, retaildevcrews/helium-csharp#55, 
retaildevcrews/helium-csharp#54)

- Java Spring Boot:  Refactoring synchronous framework to WebFlux asynchronous framework (retaildevcrews/helium-java/issues/72, retaildevcrews/helium-java/issues/70, retaildevcrews/helium-java/issues/67, retaildevcrews/helium-java/issues/71, retaildevcrews/helium-java/issues/63, retaildevcrews/helium-java/issues/77, retaildevcrews/helium-java/issues/68, retaildevcrews/helium-java/issues/69, retaildevcrews/helium-java/issues/73)

- Consolidated environments: Consolidated bluebell, gelato, sherbert and froyo for cost savings and operational efficiency while keeping security boundaries in place. #103

- All issues that need Design review are tagged: [Complete view](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3A%22design+review%22)

### Demo
- [ ] Demo completed

### Key Project Risks and Concerns

- [ ] Present Retro
- Successfully implemented private instance of Retrospected (#198) [Link](https://helium.centralus.cloudapp.azure.com/)
  - Other Dev Crews can use our private instance for their retros.
- Completed 4 sprints for M6 and 3 Engineering Surveys for M6 [Retro & Surveys](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Aretro)

- Key Outcomes:

1. **Team Dynamics**: Even though the team had a painful retro during this milestone, the commitment to ensure that Helium met the quality and developer experience bar was overwhelmingly positive.  The team rallied together to onboard new SEs, collaborated to unblock issues, and made the hard decision to start over on Java.   
2. **Engineering Excellence**: Team hyper-focused on testing (e2e, unit, parameter validations, and the developer experience across all repos; Continuous improvement around branching, PRs, CI/CD, code/design reviews, Terraform, and GitHub (automation, templates, best practices; private Retro instance); Continue evaluation of engagement against Engineering Survey.
3. **Growth Mindset**: The team has an “never give up” attitude when faced with blockers or challenges.  During this milestone, the team learned more about WebFlux, App Insights Custom Events, dev VM with multiple engineers leveraging, Terraform, GitHub Actions, and many more!  Several of the SEs completed their SE-E certifications with more coming!
4. **Sharing is Caring**: Given the challenges the team has faced, the PG reached out and asked the team to help review the Java quick starts to improve the Azure E2E experience for Java developers.  The feedback will be prioritized for ScottGu review in March.

- [ ] Discuss open risks and mitigation plans

- Java SDK for Identify and Key Vault:  Newer versions are currently available; Leveraging previous version due to security capability; Seeking clarity on SDK lifetimes and capabilities

### Backlog Review

- [ ] What is the planned for work in future sprints?

- Backlog is updated and prioritized during sprint planning every Friday; New issues are added to triage for prioritization.  [Link to Backlog](https://github.com/orgs/retaildevcrews/projects/1#column-7483734)

- Done-done on Typescript and Java repos #120, #119

- Create / update Managed Identity - Key Vault repos on github/Microsoft #195

- Create / update IETF health check repos on github.com/Microsoft #197

- Create python version of web app

- Creating shareable assets including Redbook slides (#178, #176, #175), Webcast (#143,#168, #142, #144, #145) and documentation (#167, #231), [Complete view](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Asharing)

- Continued focus on Quality and DevOps

- [X] Is additional checkpoint review needed?
- Will schedule for M7 review in April
- [ ] Is additional Game Plan review needed?

### Tasks

- [x] Upload checkpoint review to Artifact Hub
