### ISSUE TITLE
M6 Release Checklist - csharp

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium#260]
## Release
- M6 Release - helium-csharp
- v1.6.0

### Validation
- [x] All packages up to date (or task created)
- [x] Remove unused packages
- [x] Code Version updated
- [x] Code Review completed
- [x] All existing automated tests (unit and e2e) pass successfully, new tests added as needed
- [x] Code changes checked into master
- [x] Sync github actions from master template
- [x] Existing documentation is updated (readme, .md's)
- [x] New documentation needed to support the change is created
- [x] CI completes successfully
- [x] CD completes successfully
- [x] Smoke test deployed for 48 hours

### Release
- [x] Tag repo with version tag
- [x] Ensure CI-CD runs correctly
- [x] Close Release Task

## Language Checklist

- Repo [helium-csharp](/retaildevcrews/helium-csharp)

## Key Vault Secrets
- [X] Secret Name: AcrPassword
- [X] Retrieved and used from Key Vault
- [X] Secret Name: AcrUserId
- [X] Retrieved and used from Key Vault
- [X] Secret Name: AppInsightsKey
- [X] Retrieved and used from Key Vault
- [X] Secret Name: CosmosCollection
- [X] Retrieved and used from Key Vault
- [X] Secret Name: CosmosDatabase
- [X] Retrieved and used from Key Vault
- [X] Secret Name: CosmosKey
- [X] Retrieved and used from Key Vault
- [X] Secret Name: CosmosUrl
- [X] Retrieved and used from Key Vault
- [X] Runs successfully without App Insights Key secret set
- [X] Runs as expected without Cosmos secrets provided
- [X] Key Rotation Handling Implemented

## Cosmos DB
- [X] One Collection (movies)
- [X] getAllGenres query uses "VALUE" to get array of string

## Container Settings
- [X] KeyVaultName (env var)
- [X] kvname (cmd line)
- [X] AUTH_TYPE (env var)
- [X] authtype (cmd line)

## MSI to access Key Vault
- [X] App Services
- [X] CLI Cached Credentials
- [X] Visual Studio Cached Credentials

## Logging Behavior
- [X] Logging only Exceptions/Failures

## Observability/Testing
- [X] Unit Tests
- [X] Metrics reporting to dashboard
- [X] E2E integration testing running
- [X] Alerts configured

## Versioning
- [X] Version is set to 1.[Milestone].MMdd.hhmm (UTC)

## Parameter Validation
- [X] q
- [X] pageNumber
- [X] pageSize
- [X] genre
- [X] year
- [X] rating
- [X] actorId

## API Endpoints
- [X] /api/movies?q={}&genre={}&year={}&rating={}&actorId={}&pageNumber={}&pageSize={}
- [X] /api/movies/{movieId}
- [X] /api/actors?q={}&pageNumber={}&pageSize={}
- [X] /api/actors/{actorId}
- [X] /api/featured/movie
- [X] /api/genres
- [X] /robots*.txt 
- [X] /version

## Healthz
- [X] /healthz
- [X] /healthz/ietf
- [X] /healthz/dotnet

## CI-CD/Build/Deployment
- [X] Includes Dockerfile at root
- [X] Includes Dockerfile-Dev that runs locally with CLI cached credentials
- [X] CI-CD is set up in repo
- [ ] CI-CD includes e2e testing
- [X] Can be deployed with App Services
- [X] Can be deployed with AKS (using Pod Identity)

## Linting
- [X] Linter being used (fxcop)
- [X] No lint errors
- [X] Linter running in Dockerfile, fails to build if errors

## Documentation
- [x] Developer docs
- [x] Readme specific to language
- [X] Swagger Docs

**Comment by bartr** [comment]
PR submitted to address SemVer for this release. Pending a final discussion, smoke test and tagging.

We need versioning decision by noon Tuesday to hit our smoke test window.
