### ISSUE TITLE
M6 Release Checklist - typescript

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#274]
## Release
- M6 Release - typescript
- v0.6.0

### Validation
- [x] All packages up to date (or task created)
- [x] Remove unused packages
- [x] Code Version updated
- [x] Code Review completed
- [x] All existing automated tests (unit and e2e) pass successfully, new tests added as needed
- [x] Code changes checked into master
- [x] Sync github actions from master template
- [x] Existing documentation is updated (readme, .md's)
- [x] New documentation needed to support the change is created
- [x] CI completes successfully
- [x] CD completes successfully
- [x] Smoke test deployed for 48 hours

### Release
- [x] Tag repo with version tag
- [x] Ensure CI-CD runs correctly
- [x] Validate e2e testing
- [x] Close Release Task
