### ISSUE TITLE
Helium: Checkpoint Review (M7) 

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#284]
## Checkpoint Review

- M7, April 
- Review Date: April 15, 2020

### "DoneLog" Review

- [x] What was planned to be done this milestone?
    - The goal for M7 is to release Typescript 1.0, align to beta SDKs across all three languages, update C# with new SDKs, along with releasing Managed Identity Key Vault versions of C# (update) and Typescript.
- [x] What was actually done this milestone?
    - The team is currently on track to meet the M7 goal; currently halfway thru milestone.  
    - M7 is currently scheduled to end on Thursday, April 30th.
- [x] Changes in plan versus last
    - No changes in plan
- [x] Key design decisions and their outcomes
    - --dry-run feature implemented a new feature to improve dev experience, and set standard for all 3 languages, https://github.com/retaildevcrews/helium-typescript/issues/126, [all --dry-run issues](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=--dry-run)
    - Use command-line-arg's built in help for printing CLI help message which improved dev experience for Typescript, and using specific language SDK across repos https://github.com/retaildevcrews/helium-typescript/issues/125, [command line issues](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=command)
    - ability to specify a Request.Body and Request.Headers for POST requests and authentication; identified as a need for reusability https://github.com/retaildevcrews/webvalidate/issues/49
    - All issues requiring Design Review are tagged: [Compete View](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3A%22design+review%22)

### Demo
- [x] Typescript 1.0
- [x] C# system.command line

### Key Project Risks and Concerns

- [x] Present Retro
    - Completed 3 Retros and 3 Engineering Surveys [Retro & Surveys]; have 3 additional sprints for M7 (https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Aretro)
    -  Key Outcomes:
      1. Team Dynamics
      2. Peer Programming
      3. Sharing
   
- [x] Discuss open risks and mitigation plans
    - New SDKs currently in Beta 3; working the BG and will migrate as available

### Backlog Review

- [x] What is the planned for work in future sprints?
    - Backlog is updated and prioritized during sprint planning every Friday; New issues are added to triage for prioritization.  [Backlog](https://github.com/orgs/retaildevcrews/projects/1)
    - done-done on Typescript  and Java Spring Boot #120 #119 
    - Update MIKV C# Version and create Typescript & Java Spring Boot #195 
    - Create shareable assets including Redbook slides (#178, #176, #175), Webcast (#143, #168, #142, #144, #145) and documentation (#167, #231), [Complete View](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Asharing)
- [x] Is additional checkpoint review needed?
     - Will schedule M8 review in May
- [x] Is additional Game Plan review needed?
    - No

### Tasks

- [x] Upload checkpoint review to Artifact Hub

**Comment by dsturgell** [comment]
Talk Track:
1. Closing loop on Java spike
2. Typescript 1.0
3. SDK Influence (KV)
4. system.command (Beta)/New SDKs
