### ISSUE TITLE
M8 Release Checklist - webV

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#303]
## Release
- M8 Release / WebV
- v1.1.0
  - cmd line args changed, so need to increment minor version

### Validation
- [x] All packages up to date (or task created)
- [x] Remove unused packages
- [x] Code Version updated
- [x] Code Review completed
- [x] All existing automated tests (unit and e2e) pass successfully, new tests added as needed
- [x] Code changes checked into master
- [x] Sync github actions from master template
- [x] Existing documentation is updated (readme, .md's)
- [x] New documentation needed to support the change is created
- [x] CI completes successfully
- [x] CD completes successfully
- [x] Smoke test deployed for 48 hours

### Release
- [x] Resolve to-do from code
- [x] Verify all new libraries and dependencies are customer approved
- [x] Reviewed & updated readme for Developer Experience
- [x] Tag repo with version tag
- [x] Ensure CI-CD runs correctly
- [x] Ran cred scan
- [x] Removed workflow for issue triage and PR submission
- [x] Validate e2e testing
- [x] Close Release Task

**Comment by bartr** [comment]
v1.1.0 is complete
