### ISSUE TITLE
Retrospective - M7 - Sprint 4

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#314]
### Summary

# Retrospected Session

### Session details:

**Date**: Friday, April 17th, 2020 at 11:40:05 AM GMT-05:00
  
#### What went well?

- (+7/-0) Great checkpoint review!
- (+5/-0) Dashboards were a huge hit!
- (+5/-0) Presentation by Deanna, Anne and Joseph was awesome. 
- (+1/-0) MSPoll Results :)
  
#### Learned

- (+4/-0) Desire across Retail team to learn more about alerting/dashboards
- (+3/-0) System.CommandLine!
- (+2/-0) Mostly figured out how to chain calls and merge results in WebFlux!
- (+0/-0) Got a really good intro/deep dive into JAVA repo by Sanjeev.  Got to learn a bit about his set up and approach.  really cool..

#### Longed For

- (+0/-0) Velvet Taco :)
- (+0/-0) my computer to stop freezing during pair programming :(
  
#### Thanks to/for

- (+7/-0) Anne/Joseph for doing demos at CPR
- (+5/-0) Bart for driving impact out and up!
- (+2/-0) Anne for alerting variables!!
- (+2/-0) Eddie for resource explorer tips!
- (+2/-0) Sanjeev for Java support!
- (+2/-0) Tobias for cranking through the remaining typescript issues

### Action Items
  - Action: Maybe document & submit to MS Docs; feedback to CDAs; CSE feedback for alerting setup (Draco/Splunk/WMT)

### Tasks
- [x] Add Retro summary into Issue
- [ ] Create issues for relevant action items
- [ ] If final sprint for milestone. create milestone summary to share
