### ISSUE TITLE
Helium - Checkpoint Review (M8)

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#382]
This checklist is for verifying the necessary details for a checkpoint review. 

## Checkpoint Review

- M8, May
- Review Date: 5/27/2020

### Demo
_Encouraged to just replay "best of" Sprint Demo_

- [ ] Demo completed

### "DoneLog" Review

- [ ] What was planned to be done this month?
- [ ] What was actually done this month?
- [ ] Changes in plan versus last
- [ ] Key design decisions and their outcomes

### Key Project Risks and Concerns

- [ ] Present Retro
- [ ] Discuss open risks and mitigation plans

### Backlog Review

- [ ] What is the planned for work in future sprints?
- [ ] Is additional checkpoint review needed?
- [ ] Is additional Game Plan review needed?

### Tasks

- [ ] Upload checkpoint review to Artifact Hub

**Comment by wereinse** [comment]
Updated draft per our call - comments invited and I'll clean up as well.
