### ISSUE TITLE
Helium - Checkpoint Review - Final

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#430]
## Checkpoint Review

- M8, July
- Review Date: July 1, 2020

### "DoneLog" Review

- [x] What was planned to be done this month?
 - The goal for M8 is to release Java 1.0, release Managed Identity Key Vault (MIKV) and IETF for all three languages (C# Typescript, and Java), and to continue sharing best practices via documentation, webcasts, Redbooks slides and re-usability for Helium.

- [x] What was actually done this month?
- C# 1.1.0 (#435), Typescript 1.1.0 (#434), Java 1.1.0 (#306), WebValidate (#303), and IMDb 1.1.0 (#436) shipped
- Continued focused on Developer Experience (#441, #418, #397, #396, #431, #385, #165, #167)
- Continued focus on "Secure by Design" (https://github.com/retaildevcrews/helium-typescript/issues/184, https://github.com/retaildevcrews/helium-java/issues/275, https://github.com/retaildevcrews/helium-iac/pull/36, https://github.com/retaildevcrews/helium-iac/pull/37, #397, #400, https://github.com/retaildevcrews/helium-java/issues/266, https://github.com/retaildevcrews/helium-java/pull/267,https://github.com/retaildevcrews/helium-java/issues/231, https://github.com/retaildevcrews/helium-typescript/pull/176, https://github.com/retaildevcrews/imdb/pull/48, https://github.com/retaildevcrews/helium-csharp/pull/99)

- [x] Changes in plan versus last
-  Extended M8 to Wednesday, July 1st 
-  Shifted MIKV & IETF to Backlog (Work in progress)

- [x] Key design decisions and their outcomes
 - Java: Changed identity selection logic from negative to positive (https://github.com/retaildevcrews/helium-java/issues/266)
 - Updated genre query and underlining data to leverage the new feature Cosmos DB just released case insensitive searches #450 to increase performance and reduce cost
- Implement custom logging policy for KeyVault Secrets to redact secret values [CSE Feedback](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/354926)
- Publishing WebV as a .net global tool 
 - All issues requiring Design Review are tagged: [Complete View](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Ahelium+label%3A%22design+review%22)

### Demo
- [x] Helium

### Key Project Risks and Concerns

- [x] Present Retro
 - Completed 7 Retros and 7 Engineering Surveys [Retro & Surveys]; had final retro & surveys earlier today [All Retros](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Aretro) 
 - Retro Key Outcomes: 

 1. Team Dynamics 
 2. Environment for learning new things (Java, Codespaces, GitHub Actions, etc)
 3. Sharing is key (within team & within CSE)

- [x] Discuss open risks and mitigation plans
 - Closed Connection Issue (Netty): Using Spring WebFlux + the CosmosDB SDK running under consistent load for an extended duration will eventually result in a closed connection error caused by Netty.  [Azure SDK for Java Feedback submitted](https://github.com/Azure/azure-sdk-for-java/issues/10440); BG feedback fix to be incorporated in July
- Typescript NPM Package Security Issue (inversify-restify-utils) - Noted in[ readme.md file ](https://github.com/retaildevcrews/helium-typescript#dependency-vulnerability)
### Backlog Review

- [x] What is the planned for work in future sprints?
 - Backlog is current and will continue to log new issues [Complete Backlog](https://github.com/orgs/retaildevcrews/projects/1)
 - Continue to monitor open risks identified and SDK releases
 - Will leverage to onboard new team members 

- [x] Is additional checkpoint review needed?
 - None planned at this time; could add additional based on team's commitment

- [x] Is additional Game Plan review needed?
 - No

### Tasks

- [x] Upload checkpoint review to Artifact Hub
