### ISSUE TITLE
Language Comparison Tracker

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#456]
## Key Vault Secrets
- [ ] Secret Name: AcrPassword
- [ ] Retrieved and used from Key Vault
- [ ] Secret Name: AcrUserId
- [ ] Retrieved and used from Key Vault
- [ ] Secret Name: AppInsightsKey
- [ ] Retrieved and used from Key Vault
- [ ] Secret Name: CosmosCollection
- [ ] Retrieved and used from Key Vault
- [ ] Secret Name: CosmosDatabase
- [ ] Retrieved and used from Key Vault
- [ ] Secret Name: CosmosKey
- [ ] Retrieved and used from Key Vault
- [ ] Secret Name: CosmosUrl
- [ ] Retrieved and used from Key Vault
- [ ] Runs successfully without App Insights Key secret set
- [ ] Runs as expected without Cosmos secrets provided (fails)
- [ ] Key Rotation Handling Implemented

## Cosmos DB
- [ ] One Collection (movies)
- [ ] getAllGenres query uses "VALUE" to get array of string
- [ ] Use prepared SQL queries

## Support Command Line & Environment Variables 
- [ ] KEYVAULT_NAME (env var)
- [ ] --keyvault-name (cmd line)
- [ ] AUTH_TYPE (env var)
- [ ] --auth-type (cmd line)
- [ ] LOG_LEVEL (env var)
- [ ] --log-level (cmd line)
- [ ] --dry-run (cmd line) 
- [ ] --help (cmd line) 
- [ ] --version (C#)

## MSI to access Key Vault
- [ ] App Services
- [ ] CLI Cached Credentials
- [ ] Visual Studio Cached Credentials (not supported other than Windows)
- [ ] MSI required/enforced in production

## Logging Behavior
- [ ] Logging only Exceptions/Failures by default

## Observability/Testing
- [ ] Unit Tests
- [ ] Metrics reporting to dashboard
- [ ] E2E integration testing running
- [ ] Alerts configured (Infra not apps)

## Versioning
- [ ] Version is set to 1.0.[Milestone]+MMdd.HHmm (UTC)

## Parameter Validation (update API Spec to this in .md file)
- [ ] q
- [ ] pageNumber
- [ ] pageSize
- [ ] genre
- [ ] year
- [ ] rating
- [ ] actorId

## API Endpoints
- [ ] /api/movies?q={}&genre={}&year={}&rating={}&actorId={}&pageNumber={}&pageSize={}
- [ ] /api/movies/{movieId}
- [ ] /api/actors?q={}&pageNumber={}&pageSize={}
- [ ] /api/actors/{actorId}
- [ ] /api/featured/movie
- [ ] /api/genres

**Middleware **
- [ ] /robots*.txt 
- [ ] /version

## Healthz 
- [ ] /healthz
- [ ] /healthz/ietf

## CI-CD/Build/Deployment  
- [ ] Includes Dockerfile at root
- [ ] CI-CD is set up in repo
- [ ] CI-CD includes e2e testing
- [ ] Can be deployed with App Services
- [ ] Can be deployed with AKS (using Pod Identity)
- [ ] PRs code changes are deployed to e2e testing environment

## Linting
- [ ] Linter being used (tslint)
- [ ] No lint errors
- [ ] Linter running in Dockerfile, fails to build if errors

## Documentation
- [ ] Developer docs
- [ ] Supports Codespaces and documents proper uses
- [ ] Repo contains use of .devcontainer 
- [ ] Readme specific to language
- [ ] Readme consistent with latest changes (design review 6/9)
- [ ] Use shared Swagger Docs
