### ISSUE TITLE
Helium M9

### ISSUE THREAD

**Issue by bartr** [retaildevcrews/helium#465]
This checklist is for verifing the release is ready to publish and published correctly.

## Release
- Helium M9
- v1.2.9

## Themes
- Introducing new team to the CSE process
- Complete the sharing tasks
- Respond to feedback (CPR and customer)

## Tasks

- Finish sharing tasks

- Address CP Review Feedback
  - [ ] Deploy webv to multiple locations per service #461 
  - [ ] Look into CLI / code generator for helium #464 
  - [ ] Rebuild releases that are binary compatible #462 

Update to new SDKs
  - [ ] csharp
  - [ ] java
  - [ ] typescript
  - [ ] webv
  - [ ] imdb

Ship / update MIKV
  - [ ] csharp
  - [ ] java
  - [ ] typescript

Ship / update IETF
  - [ ] csharp
  - [ ] java
  - [ ] typescript

### Validation
- [ ] All packages up to date (or task created)
- [ ] Remove unused packages
- [ ] Code Version updated
- [ ] Code Review completed
- [ ] All existing automated tests (unit and e2e) pass successfully, new tests added as needed
- [ ] Code changes checked into master
- [ ] Sync github actions from master template
- [ ] Existing documentation is updated (readme, .md's)
- [ ] New documentation needed to support the change is created
- [ ] CI completes successfully
- [ ] CD completes successfully
- [ ] Smoke test deployed for 48 hours

### Release
- [ ] Reviewed & updated readme for Developer Experience
- [ ] Resolve to-do from code
- [ ] Verify all new libraries and dependencies are customer approved
- [ ] Tag repo with version tag
- [ ] Ensure CI-CD runs correctly
- [ ] Ran cred scan
- [ ] Removed workflow for issue triage and PR submission
- [ ] Validate e2e testing
- [ ] Close Release Task
