### ISSUE TITLE
Helium - Checkpoint Review - M9

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#489]
## Checkpoint Review

- M9, August
- Review Date: 8/12/2020

### Reuse & Impact
- Continuing to incorporate customer and internal feedback (i.e FedEx, Kroger, potentially P&G)
- Contributing to official Azure SDK team blog per request (Sept)

### "DoneLog" Review

- [x] What was planned to be done this month?
- Focus for M9 is to respond to feedback from CPR, Language Comparison Webcast, and customers,  as well as onboard new team members.   (#465, #493, https://github.com/retaildevcrews/webvalidate/issues/95)
 - The team also wanted to complete the [Sharing](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3ASharing) tasks from M8.

- [x] What was actually done this month?
 - Incorporated feedback:
   - Deploy webv to multiple locations per service #461
   - Look into CLI / code generator for helium #464
   - Rebuild releases that are binary compatible #462 
   - Made decision to combine Observability & WebV webcast into a e2e testing webcast (will be recorded soon) (#499)
   - Spike on "Bring Your Own Database" for WebV (FedEx)  https://github.com/retaildevcrews/webvalidate/issues/92
   - Create debug image to WebV for allow for deeper investigation into latency test behavior (#467, https://github.com/retaildevcrews/webvalidate/pull/94, Create debug image to WebV for allow for deeper investigation into latency test behavior (#467, retaildevcrews/webvalidate#94, https://github.com/retaildevcrews/webvalidate/issues/97)
- Switched from App Insights to Log Analytics for WebV (https://github.com/retaildevcrews/webvalidate/issues/90, #482, #481, https://github.com/retaildevcrews/webvalidate/issues/97)
- Resolved NPM package vulnerability (https://github.com/retaildevcrews/helium-typescript/issues/112, https://github.com/retaildevcrews/helium-typescript/pull/187)
-  Shared [Helium Language Comparison Webcast](https://aka.ms/HeliumLangComparison)
- Continue to improve Java developer experience: Unit Test Bugs (https://github.com/retaildevcrews/helium-java/issues/284, https://github.com/retaildevcrews/helium-java/issues/283), Fixed deprecated swagger annotations (https://github.com/retaildevcrews/helium-java/pull/285, https://github.com/retaildevcrews/helium-java/issues/282), Built java custom issue for Codespaces & updating to JDK 11 (https://github.com/retaildevcrews/helium/issues/513, https://github.com/retaildevcrews/helium-java/issues/287)

- [x] Changes in plan versus last
- Added feature to WebV enabling substitute environment variables per customer feedback

- [x] Key design decisions and their outcomes
- Validating RESTfulness of our APIs referencing the [Microsoft API guidelines](https://github.com/microsoft/api-guidelines) (#493)
- Switched from App Insights to Log Analytics for WebV due to improved developer experience and seamless integration into ACI
- Support Environment variables for testing in WebV to allow substitute environment variables to enable OAuth and other tokens (per FedEx request, https://github.com/retaildevcrews/webvalidate/issues/95, https://github.com/retaildevcrews/webvalidate/pull/96)

### Demo
- [x] Demo completed
 - Adjusting Version Endpoint 
 - Improvements to WebV
 - Custom Java image

### Key Project Risks and Concerns

- [x] Present Retro
- Completed 2 Retros and 2 Engineering Surveys;  [All Retros](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Aretro) 
- Retro Key Outcomes: 
  - Team Dynamics 
  - Environment for learning new things (onboarding)
  - Sharing is key (within team & within CSE)

- [x] Discuss open risks and mitigation plans
 - Due to other commitments, time to focus has been limited; plans to allocate more focused time in future 

### Backlog Review

- [x] What is the planned for work in future sprints?
 - Continue to incorporate feedback, including:
    - Schedule e2e testing webcast #499 
   - Continue to validate RESTfulness of our APIs referencing the [Microsoft API guidelines](https://github.com/microsoft/api-guidelines) (#493)
   - Updating docs to explicitly call out "best practices" (#495)
   - Measure velocity of setting up Helium to understand the impact & value
- Resolve Netty Resource Leak Issue (#253)
 - Continue to leverage to onboard new team members [good-first-issue](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Agood-first-issue)
 - Continue to monitor open risks identified and SDK releases https://github.com/retaildevcrews/helium-typescript/issues/152
 - Backlog is current and will continue to log new issues [Complete Backlog](https://github.com/orgs/retaildevcrews/projects/1)

- [x] Is additional checkpoint review needed?
 - Yes

- [x] Is additional Game Plan review needed?
 - No

### Tasks

- [ ] Upload checkpoint review to Artifact Hub
