### ISSUE TITLE
Helium - Checkpoint Review - Done-Done

### ISSUE THREAD

**Issue by dsturgell** [retaildevcrews/helium#548]
## Helium - Checkpoint Review (Done-Done)

- M9 Done-Done, September
- September 10, 2020

### "DoneLog" Review
- [x] What was planned to be done this month?
 - The main focus this month was to continue incorporating feedback from CPR, Language Comparison Webcast, and customers, as well as onboard new team members.  
 - The team also wanted to complete the [Sharing](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3ASharing) tasks from M8

- [x] What was actually done this month?
 - Modify Terraform per customer feedback (starting with a public AKS cluster and iterating towards a private cluster)  #https://github.com/retaildevcrews/helium-terraform/issues/40, #https://github.com/retaildevcrews/helium-terraform/issues/31
 - Continue to validate RESTfulness of our APIs referencing the [Microsoft API guidelines](https://github.com/microsoft/api-guidelines) (#493, #111 )
- Resolved Netty Resource Leak Issue (#253 )
-  Continued improvement to [CI/CD process](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=ci) 
 - Continue to leverage to onboard new team members [good-first-issue](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Agood-first-issue)

- [x] Changes in plan versus last
 - Responded to customer feedback

- [x] Key design decisions and their outcomes
- CI/CD: Adding tags/flags (i.e: experimental, production) in combination with conditional compilation which allows us to specify which features of code are built and deployed.  
- CI/CD: Deleting/cancelling pull request will revert test environment to previously deployed code
- CI/CD: Quality assurance check to validate links in documentation are valid and working

### Demo
- [x] Demo completed

### Key Project Risks and Concerns
- [x] Present Retro
- Completed 3 Retros and 3 Engineering Surveys;  [All Retros](https://github.com/orgs/retaildevcrews/projects/1?card_filter_query=label%3Aretro) 
- Retro Key Outcomes: 
  - Team Dynamics 
  - Environment for learning new things (onboarding)
  - Sharing is key (within team & within CSE)

- [x] Discuss open risks and mitigation plans
- ASP.NET Core Model Binding Exception (Enumeration Issue): When running load test of ASP.NET core web API, HTTP/500 errors were observed. [CSE Feedback](https://dev.azure.com/csefy19/CSE%20Feedback/_workitems/edit/385454)

### Backlog Review

- [x] What is the planned for work in future sprints?
 - Team will continue to drive reusability 
 
- [x] Is additional checkpoint review needed?
 - No

- [x] Is additional Game Plan review needed?
- No

### Tasks

- [x] Upload checkpoint review to Artifact Hub

**Comment by dsturgell** [comment]
Workflow:
- Set Stage (Already done with code, focusing on internal/external feedback and sharing tasks)
- Impact (drove/continue to drive; resuability)
-  Customer Feedback spotlight - AKS (AK)
-  Dev Experience spotlight (Siva)
- Demo: Standardizing api changes (hybrid solution, providing feedback)  (Siva/TBD)
- Engineering Fundamentals - core to team and our team culture, EE Survey
- Reference Sharing tasks completed & where to find them

@AAkindele @sivamu @aflinchb @bartr

**Comment by sivamu** [comment]
During the Customer feedback spot, I can talk about the Java package updates as well as `PartitionKey` refactor changes.
